### ISSUE TITLE
Its also target Message button

### ISSUE THREAD

**Issue by orrans** [felladrin/linkedin-autoconnect-chrome-extension#19]
When in the page i have already some connection its press on the message button as well and open the message tab on the bottom of the page

**Comment by felladrin** [comment]
Hi @orrans, thanks for reporting it.
I confirm it's a bug, but at this moment, LinkedIn doesn't provide any info we could use to differentiate the "message" button from the "connect" one. And we can't filter it by the text, because if user is using LinkedIn in a language other than English, it would fail to find the button.

For now, please select only 2nd connections on this filter menu, so none of the results shall display the "message" button.

![image](https://user-images.githubusercontent.com/418083/118874592-c1a03d80-b8f3-11eb-9fb1-f08004713119.png)

**Comment by felladrin** [comment]
Fixed by https://github.com/felladrin/linkedin-autoconnect-chrome-extension/commit/0460c28502e80bf167d52ea565cf07b5f5c268e1 and available in [LinkedIn AutoConnect v2.0.1](https://github.com/felladrin/linkedin-autoconnect-chrome-extension/releases/tag/v2.0.1).
