### ISSUE TITLE
Repo folder structure doesn't work out of the box

### ISSUE THREAD

**Issue by oneshot-engineering** [felladrin/linkedin-autoconnect-chrome-extension#507]
### Bug description

manifest file is not in right place and also tab.js doesn't exist thats mentioned in the file

### Steps to reproduce

clone, try to load the repo into chrome://extensions

**Comment by felladrin** [comment]
Hi, @oneshot-engineering!

Thank you for taking the time to check it out.

The repository is indeed not in the extension format. Please note that the instructions in the Readme indicate that, to use the extension, users should download the .zip file from the Releases page, which has it pre-built.

But you can also build it yourself. Since you have already cloned the repo and have Node.js installed, you can run `npm ci && npm run build`. This will create the extension correctly structured inside the `dist` folder.

Kindly let me know if this resolves the issue.
